### ISSUE TITLE
Enable .gz files

### ISSUE THREAD

**Issue by boh1996** [diku-dk/futhark-benchmark-dashboard#12]
Currently the frontend requests none gzip files. So either the frontend should be configured to request .gz files or the webserver should be configured to always serve .gz files if they exists.

**Comment by fredefl** [comment]
Sounds good @Athas! Also, the `gzip` files are run with the most thorough compression mode `gzip` offers - I am not sure whether an HTTP server would want to use the `slowest` mode.

**Comment by fredefl** [comment]
An update on this:
When using the `.gz` files, the webserver must support using the `Content-Encoding` header for the file, for the browser to correctly decode the file - otherwise the browser will not recognize the gzip format. This it might be easier to have the webserver configured for gzip. This is completely up to you though - either solution works for me. @Athas

**Comment by fredefl** [comment]
Fixed by #17
